Advanced Building Blocks - Enumerables
KartheeKWD/Enumerable-Methods pull request #3
Opened 2021-02-08 09:59 UTC by KartheekWD

2021-02-08 10:23 UTC, mimipeshy commented on enumerables.rb
> +  def my_all?
- [ ] enumerables #my_all? when no block or argument is given returns true when none of the collection members are false or nil
- [ ] enumerables #my_all? when no block or argument is given returns false when one of the collection members are false or nil
- [ ] enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- [ ] enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- [ ] enumerables #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class
- [ ] enumerables #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] enumerables #my_all? when a Regex is passed as an argument returns false if any of the collection does not match the Regex
- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern

2021-02-08 10:24 UTC, mimipeshy reviewed
### STATUS: CHANGES REQUIRED 🔴 ♻️ 

Hey there @KartheekWD and @Arinpe this is a great job you guys have done for a first review 👏🏾 👏🏾  Most of the methods are working as expected except the following:

- [ ] Check out comments below

2021-02-08 10:28 UTC, mimipeshy commented on enumerables.rb
> +
- [ ]  enumerables #my_all? when no block or argument is given returns true when none of the collection members are false or nil
- [ ]  enumerables #my_all? when no block or argument is given returns false when one of the collection members are false or nil
- [ ]  enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- [ ] enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- [ ] enumerables #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class
- [ ] enumerables #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] enumerables #my_all? when a Regex is passed as an argument returns false if any of the collection does not match the Regex
- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern

2021-02-08 10:29 UTC, mimipeshy commented on enumerables.rb
> +
- [ ] enumerables #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] enumerables #my_any? when no block or argument is given returns false if at least one of the collection is not true
- [ ] enumerables #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- [ ] enumerables #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
- [ ] enumerables #my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex
- [ ] enumerables #my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ]  enumerables #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- [ ]  enumerables #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern

2021-02-08 10:31 UTC, mimipeshy commented on enumerables.rb
> +
- [ ] enumerables #my_none? when no block or argument is given returns true only if none of the collection members is true
- [ ] enumerables #my_none? when no block or argument is given returns false only if one of the collection members is true
- [ ] enumerables #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] enumerables #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
- [ ] enumerables #my_none? when a class is passed as an argument returns false if any of the collection is a member of such class
- [ ]  enumerables #my_none? when a Regex is passed as an argument returns true if none of the collection matches the Regex
- [ ]  enumerables #my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex
- [ ] enumerables #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ]  enumerables #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

2021-02-08 10:33 UTC, mimipeshy commented on enumerables.rb
> +
# enumerables #multiply_els - his method fails because its not an actual enumerable, To solve it,move this method outside the Enumerable  module

2021-02-08 10:34 UTC, mimipeshy reviewed
Done

2021-02-08 10:35 UTC, mimipeshy commented on enumerables.rb
> +
enumerables #my_all? when no block or argument is given returns true when none of the collection members are false or nil
 enumerables #my_all? when no block or argument is given returns false when one of the collection members are false or nil
 enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
 enumerables #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric

2021-02-10 07:45 UTC, rindrajosia requested changes
**Changes required** :red_circle: 
Hello!!
Well done job so far. However, there are bugs to fix:

- [x] [REQUIRED] Add a description to your pull request.
- [x] [REQUIRED] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- [x] [REQUIRED] #my_any? when no block or argument is given returns false if at least one of the collection is not true
- [x] [REQUIRED] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- [x] [REQUIRED] #my_none? when no block or argument is given returns true only if none of the collection members is true
- [x] [REQUIRED] #my_none? when no block or argument is given returns false only if one of the collection members is true
- [ ] [REQUIRED] #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject

Kindly make the changes and submit a new code review request.
Thanks

Rindra Josia

2021-02-11 13:35 UTC, arslanbisharat requested changes
### Changes required 🔴

Hello!!

Well done job so far. However, there are bugs to fix:

- [ ] enumerables #my_all? when a class is passed as an argument returns false if any 
of the collection is not a member of such class

- [ ] enumerables #my_any? when no block or argument is given returns false if at least one of the collection is not true
- [ ]  enumerables #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ] enumerables #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

Kindly make the changes and submit a new code review request.

Thanks
Arslan Bisharat

2021-02-12 14:46 UTC, BrianSammit requested changes
CHANGES REQUIRED!! :recycle: :red_circle: 
-------------------
Hello team!! :wave: You are doing an amazing job on the changes :wrench: 
There are a few changes to make to fully complete this project. :muscle: 
-------------------- 

- [x] Remember to set up your `development` as the default branch on GitHub. [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) you can refresh on how to set up the branch. 
- [x] Delete or keep on another branch all of the debugging code you used to test your enumerables. [Here](https://questions.microverse.org/t/debugging-instructions-code/346) you can read the reason why you shouldn't commit debugging code.
- [x] You have an undefined local variable or method `data` in `my_none?` line 82. That gives you troubles when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern. 
- [x] #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class. Instead is returning True.
- [x] #my_any? when no block or argument is given returns false if at least one of the collection is not true. Instead of false is returning True.
-----------------
Work on that request and send it for another review. :muscle: :smile: 
HAPPY CODDING!! 

![200 (1)](https://user-images.githubusercontent.com/64173189/107782335-ed20f400-6d16-11eb-9b43-c1f766e72c8d.gif)

2021-02-12 14:46 UTC, BrianSammit commented on enumerables.rb
> +# p [1, 2, 3].my_none?(4) # => true
Kindly delete or move to another branch all of this debugging code. :hammer_and_wrench: :+1:

2021-02-15 10:47 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @KartheekWD and @Arinpe  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] #my_any? method failed one test case, please read the details in comment I put inline
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-02-15 10:47 UTC, descholar-ceo commented on enumerables.rb
> +
### #my_any? when no block or argument is given returns false if at least one of the collection is not true

2021-02-15 13:45 UTC, mke2111 approved these changes
# **🎉 STATUS: APPROVED 🎉** 

## Hey @mimipeshy  & @KartheekWD,
 **Congratulations 🥳 🥂 . The tests for our enumerable methods pass. Thank you for making all the requested changes that have brought you this far.**

- [ ] [REQUIRED] Kindly correct the cloning process in the readme file. `.git` is missing.

**You may now merge to the develop branch and submit a project completion form. 👍🏽** 

## Cheers!! 🍹 

## Reach me on slack for a chitchat 🆘  **Roy Mukuye**

2021-02-15 13:58 UTC, merged